
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usmankashif
 */
public class CoCurricular_Interface extends javax.swing.JFrame {
    /**
     * Creates new form CoCurricular_Interface
     */
    public CoCurricular_Interface() {
        initComponents();
        setLocation(270,170); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FootballVideo = new javax.swing.JButton();
        CricketButton = new javax.swing.JButton();
        javax.swing.JButton Tennis_Interface = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TennisButton = new javax.swing.JButton();
        FootballButton = new javax.swing.JButton();
        javax.swing.JButton HomeButton = new javax.swing.JButton();
        BasketBallButton = new javax.swing.JButton();
        VolleyBallButton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Myanmar MN", 0, 36)); // NOI18N
        jLabel3.setText("Consume The Calming Quiz!");
        jLabel3.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("<html> <center> The Calming Quiz aspires to inspire. It provides youthful students with endless purpose and a reason for hardwork. <br> Through this innovative and engaging\t\t\t\t\t\t\t quiz, discover task-specific motivation in order to increase <i> <b> your </b> </i> productivity </center> </br> </html> \t\t\t\t\t\t\t");

        jButton4.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 210, 233));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 158, 235), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 442));
        jPanel1.setSize(new java.awt.Dimension(3333, 100));

        jLabel5.setFont(new java.awt.Font("Hiragino Sans GB", 1, 36)); // NOI18N
        jLabel5.setText("<html> <b> Co-Curriculars; One-Way Stop for <br> <center> Endless Support in Sport </center> </b> </html\n");
        jLabel5.setAutoscrolls(true);

        jLabel9.setFont(new java.awt.Font("Hiragino Sans GB", 1, 17)); // NOI18N
        jLabel9.setText("<html> <b> <center> Sport is not only a fruitful way to remain physically fit,  <br>  but it provides us with an escape from all of life's troubles.  <br> <br> Whether you simply want to indulge into the sports <br> state of mind, or even possibly have an upcoming event, <br> <u> click an icon to visit <i> your </i> sport's motivation</u>. <br> Alternatively, press the home icon to return </center> </b> </html>");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BlueHorizontalLine.png"))); // NOI18N

        FootballVideo.setText("test");
        FootballVideo.setBorder(null);
        FootballVideo.setBorderPainted(false);
        FootballVideo.setContentAreaFilled(false);
        FootballVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FootballVideoActionPerformed(evt);
            }
        });

        CricketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CricketButton.png"))); // NOI18N
        CricketButton.setBorderPainted(false);
        CricketButton.setContentAreaFilled(false);
        CricketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricketButtonActionPerformed(evt);
            }
        });

        Tennis_Interface.setText("jButton1");
        Tennis_Interface.setBorder(null);
        Tennis_Interface.setBorderPainted(false);
        Tennis_Interface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tennis_InterfaceActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");

        TennisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TennisButton.png"))); // NOI18N
        TennisButton.setBorderPainted(false);
        TennisButton.setContentAreaFilled(false);
        TennisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TennisButtonActionPerformed(evt);
            }
        });

        FootballButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FootballButton.png"))); // NOI18N
        FootballButton.setBorder(null);
        FootballButton.setBorderPainted(false);
        FootballButton.setContentAreaFilled(false);
        FootballButton.setDefaultCapable(false);
        FootballButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FootballButtonActionPerformed(evt);
            }
        });

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        BasketBallButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BasketBallButton.png"))); // NOI18N
        BasketBallButton.setBorderPainted(false);
        BasketBallButton.setContentAreaFilled(false);
        BasketBallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketBallButtonActionPerformed(evt);
            }
        });

        VolleyBallButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VolleyBallButton.png"))); // NOI18N
        VolleyBallButton.setBorderPainted(false);
        VolleyBallButton.setContentAreaFilled(false);
        VolleyBallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolleyBallButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(799, 799, 799))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(890, 890, 890)
                        .addComponent(jLabel8)
                        .addGap(762, 762, 762)))
                .addComponent(jLabel7)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(FootballVideo)
                                .addGap(179, 179, 179)
                                .addComponent(Tennis_Interface))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(739, 739, 739)
                                .addComponent(jButton5)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(456, 456, 456)
                            .addComponent(jLabel12)
                            .addGap(203, 203, 203)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(FootballButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(VolleyBallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(BasketBallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TennisButton))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(CricketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TennisButton)
                            .addComponent(BasketBallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CricketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(VolleyBallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FootballButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(308, 308, 308)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FootballVideo)
                    .addComponent(Tennis_Interface))
                .addGap(1340, 1340, 1340)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(333, 333, 333)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FootballVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FootballVideoActionPerformed
 
    }//GEN-LAST:event_FootballVideoActionPerformed

    private void Tennis_InterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tennis_InterfaceActionPerformed
        // TODO add your handling code here:
        new Tennis_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_Tennis_InterfaceActionPerformed

    private void CricketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricketButtonActionPerformed
        // TODO add your handling code here
        new Cricket_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_CricketButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        new Welcome_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void FootballButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FootballButtonActionPerformed
        // TODO add your handling code here:
        new Football_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_FootballButtonActionPerformed

    private void VolleyBallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolleyBallButtonActionPerformed
        // TODO add your handling code here:
        new Volleyball_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_VolleyBallButtonActionPerformed

    private void BasketBallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketBallButtonActionPerformed
        // TODO add your handling code here:
        new BasketBall_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_BasketBallButtonActionPerformed

    private void TennisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TennisButtonActionPerformed
        // TODO add your handling code here:
        new Tennis_Interface().setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_TennisButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoCurricular_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoCurricular_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoCurricular_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoCurricular_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoCurricular_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasketBallButton;
    private javax.swing.JButton CricketButton;
    private javax.swing.JButton FootballButton;
    private javax.swing.JButton FootballVideo;
    private javax.swing.JButton TennisButton;
    private javax.swing.JButton VolleyBallButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
